name: Workflow 5

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *" 

jobs:
  first-action:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: .github/actions/first-action@v1
        with:
          who-to-greet: 'Someone'
      - name: Check if input and output are same
        if: ${{ steps.foo.outputs.who-was-greeted == 'Someone' }}
        run: echo input output matches.
